# Generated by Django 3.1.7 on 2021-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesItem',
            fields=[
                ('title', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False)),
                ('pf_index', models.IntegerField()),
                ('rid', models.CharField(max_length=20)),
                ('quality', models.IntegerField()),
            ],
        ),
    ]
